name: Denvig

quickActions:
  - check
  - codegen
  - compile
  - lint:fix
  - test:ci

services:
  hello:
    command: |
      node -e "require('http').createServer((req, res) => { res.writeHead(200, {'Content-Type': 'text/plain'}); res.end('Hello World\n'); }).listen(process.env.PORT, () => console.log(`Server running at http://localhost:${process.env.PORT}/`))"
    port: 8080
  wontlaunch:
    command: |
      node -e "throw new Error('This service is intended to fail to launch')"
    port: 8080

actions:
  check:
    command: |
      pnpm run check-types
      pnpm run lint
      pnpm run test
      pnpm run build
      node dist/cli.cjs version
      denvig run compile
      denvig version
  compile:
    command: |
      denvig run compile:darwin-x64
      denvig run compile:darwin-arm64
      denvig run compile:linux-x64
      denvig run compile:linux-arm64
  "compile:darwin-x64":
    command: bun build --compile --minify --bytecode --target bun-darwin-x64 --outfile releases/denvig-darwin-x64-$(denvig version) src/cli.ts
  "compile:darwin-arm64":
    command: bun build --compile --minify --bytecode --target bun-darwin-arm64 --outfile releases/denvig-darwin-arm64-$(denvig version) src/cli.ts
  "compile:linux-x64":
    command: bun build --compile --minify --bytecode --target bun-linux-x64-modern --outfile releases/denvig-linux-x64-$(denvig version) src/cli.ts
  "compile:linux-arm64":
    command: bun build --compile --minify --bytecode --target bun-linux-arm64 --outfile releases/denvig-linux-arm64-$(denvig version) src/cli.ts
