import { deepStrictEqual, strictEqual } from 'node:assert'
import { it } from 'node:test'

import { parseYarnLockForDedupe } from './parse-yarn.ts'

it('handles simple dependencies with no duplicates', () => {
  const result = parseYarnLockForDedupe(`
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1

react@^18.2.0:
  version "18.2.0"
  resolved "https://registry.yarnpkg.com/react/-/react-18.2.0.tgz#test"
  integrity sha512-test==
  `)

  strictEqual(Object.keys(result.dependencies).length, 1)
  deepStrictEqual(result.dependencies.react.versions, {
    '18.2.0': ['^18.2.0'],
  })
})

it('handles multiple versions with optimisation', () => {
  const result = parseYarnLockForDedupe(`
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1

react@^18.2.0:
  version "18.2.0"
  resolved "https://registry.yarnpkg.com/react/-/react-18.2.0.tgz#test1"
  integrity sha512-test1==

react@^18.1.0, react@^18.1.2:
  version "18.1.3"
  resolved "https://registry.yarnpkg.com/react/-/react-18.1.3.tgz#test2"
  integrity sha512-test2==
  `)

  strictEqual(Object.keys(result.dependencies).length, 1)
  deepStrictEqual(Object.keys(result.dependencies.react.versions), [
    '18.1.3',
    '18.2.0',
  ])
  deepStrictEqual(result.dependencies.react.optimisedVersions, {
    '18.2.0': ['^18.1.0', '^18.1.2', '^18.2.0'],
  })
})
