import { strictEqual } from 'node:assert'
import { it } from 'node:test'

import { prepareYarnRemovals } from './prepare-removals-yarn.ts'

it('removes specified dependency blocks from yarn.lock', () => {
  const source = `
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1

react@^18.2.0:
  version "18.2.0"
  resolved "https://registry.yarnpkg.com/react/-/react-18.2.0.tgz#test1"
  integrity sha512-test1==

react@^7.1.2:
  version "7.1.3"
  resolved "https://registry.yarnpkg.com/react/-/react-7.1.3.tgz#test2"
  integrity sha512-test2==

react@^18.1.0, react@^18.1.3:
  version "18.1.3"
  resolved "https://registry.yarnpkg.com/react/-/react-18.1.3.tgz#test3"
  integrity sha512-test3==
`

  const result = prepareYarnRemovals(source, { react: ['18.2.0'] })

  // react@18.2.0 block should be removed
  strictEqual(result.includes('18.2.0'), false)

  // Other blocks should remain
  strictEqual(result.includes('7.1.3'), true)
  strictEqual(result.includes('18.1.3'), true)
})
