name: Build

permissions:
  contents: read

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4


      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.4

      - name: Install dependencies
        run: deno install

      - run: deno task lint

      - run: deno task build

      - run: deno task cli version
