name: main

permissions:
  contents: read

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4


      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.4

      - name: Install dependencies
        run: deno install

      - name: Install Biome
        run: |
          curl -L https://github.com/biomejs/biome/releases/download/@biomejs/biome@2.1.3/biome-linux-x64 -o biome
          chmod +x biome
          mv biome /usr/local/bin/biome

      - run: deno task lint

      - name: Run build
        run: |
          deno task build
          ls -lh dist/

      - run: deno task cli version
