name: main

permissions:
  contents: read

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  # Workspace is /home/runner/work/denvig/denvig so we want /home/runner/work as the root
  DENVIG_CODE_ROOT_DIR: ${{ github.workspace }}/../..

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.18"

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: "10.14"

      - name: Install dependencies
        run: pnpm install

      - name: Run lint
        run: pnpm run lint

      - name: Run tests
        run: pnpm run test

      - name: Check version
        run: bin/denvig-dev version

      - name: Compile binaries for all platforms
        run: denvig run compile
