import { deepStrictEqual, strictEqual } from 'node:assert'
import { describe, it } from 'node:test'

import { parseYarnLockContent } from './yarn.ts'

describe('parseYarnLockContent()', () => {
  it('handles simple dependencies with sources', () => {
    const result = parseYarnLockContent(`
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1

"@types/react@*", "@types/react@^18.2.15":
  version "18.2.79"
  resolved "https://registry.yarnpkg.com/@types/react/-/react-18.2.79.tgz#c40efb4f255711f554d47b449f796d1c7756d865"
  integrity sha512-RwGAGXPl9kSXwdNTafkOEuFrTBD5SA2B3iEB96xi8+xu5ddUa/cpvyVCSNn+asgLCTHkb5ZxN8gbuibYJi4s1w==
  dependencies:
    "@types/prop-types" "*"
    csstype "^3.0.2"

react@^18.2.0:
  version "18.2.0"
  resolved "https://registry.yarnpkg.com/react/-/react-18.2.0.tgz#555bd98592883255fa00de14f1151a917b5d77d5"
  integrity sha512-/3IjMdb2L9QbBdWiW5e3P2/npwMBaU9mHCSCUzNln0ZCYbcfTsGbTJrU/kGemdH2IWmB2ioZ+zkxtmq6g09fGQ==
  dependencies:
    loose-envify "^1.1.0"

loose-envify@^1.1.0:
  version "1.4.0"
  resolved "https://registry.yarnpkg.com/loose-envify/-/loose-envify-1.4.0.tgz#71ee51fa7be4caec1a63839f7e682d8132d30caf"
  integrity sha512-lyuxPGr/Wfhrlem2CL/UcnUc1zcqKAImBDzukY7Y5F/yQiNdko6+fRLevlw1HgMySw7f611UIY408EtxRSoK3Q==
  `)

    // 5 dependencies: @types/react, react, loose-envify, @types/prop-types (transitive), csstype (transitive)
    strictEqual(Object.keys(result.dependencies).length, 5)

    // Direct dependencies have 'yarn.lock' as source
    deepStrictEqual(result.dependencies['@types/react'], {
      versions: {
        '18.2.79': { 'yarn.lock': '^18.2.15' },
      },
    })

    deepStrictEqual(result.dependencies.react, {
      versions: {
        '18.2.0': { 'yarn.lock': '^18.2.0' },
      },
    })

    // Transitive dependencies have 'yarn.lock:parent@version' as source
    // These don't have their own lockfile entries, so versions is empty
    deepStrictEqual(result.dependencies['@types/prop-types'], {
      versions: {},
    })

    deepStrictEqual(result.dependencies.csstype, {
      versions: {},
    })

    // loose-envify is both directly referenced and a transitive dep
    deepStrictEqual(result.dependencies['loose-envify'], {
      versions: {
        '1.4.0': {
          'yarn.lock': '^1.1.0',
          'yarn.lock:react@18.2.0': '^1.1.0',
        },
      },
    })
  })

  it('handles multiple versions of the same dependency', () => {
    const result = parseYarnLockContent(`
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1

react@^18.2.0:
  version "18.2.0"
  resolved "https://registry.yarnpkg.com/react/-/react-18.2.0.tgz#555bd98592883255fa00de14f1151a917b5d77d5"
  integrity sha512-/3IjMdb2L9QbBdWiW5e3P2/npwMBaU9mHCSCUzNln0ZCYbcfTsGbTJrU/kGemdH2IWmB2ioZ+zkxtmq6g09fGQ==
  dependencies:
    loose-envify "^1.1.0"

react@^7.1.2:
  version "7.1.3"
  resolved "https://registry.yarnpkg.com/react/-/react-18.2.0.tgz#555bd98592883255fa00de14f1151a917b5d77d9"
  integrity sha512-/3IjMdb2L9QbBdWiW5e3P2/npwMBaU9mHCSCUzNln0ZCYbcfTsGbTJrU/kGemdH2IWmB2ioZ+zkxtmq6g09fG7==

react@^18.1.0, react@^18.1.3, react@^18.1.2:
  version "18.1.3"
  resolved "https://registry.yarnpkg.com/react/-/react-18.1.0.tgz#555bd98592883255fa00de14f1151a917b5d77d1"
  integrity sha512-/3IjMdb2L9QbBdWiW5e3P2/npwMBaU9mHCSCUzNln0ZCYbcfTsGbTJrU/kGemdH2IWmB2ioZ+zkxtmq6g09fGV==
  dependencies:
    loose-envify "^1.0.9"

loose-envify@^1.0.9, loose-envify@^1.1.0:
  version "1.4.0"
  resolved "https://registry.yarnpkg.com/loose-envify/-/loose-envify-1.4.0.tgz#71ee51fa7be4caec1a63839f7e682d8132d30caf"
  integrity sha512-lyuxPGr/Wfhrlem2CL/UcnUc1zcqKAImBDzukY7Y5F/yQiNdko6+fRLevlw1HgMySw7f611UIY408EtxRSoK3Q==
  `)

    // Check react has multiple versions with sources
    deepStrictEqual(Object.keys(result.dependencies.react.versions), [
      '7.1.3',
      '18.1.3',
      '18.2.0',
    ])

    deepStrictEqual(result.dependencies.react.versions['7.1.3'], {
      'yarn.lock': '^7.1.2',
    })

    deepStrictEqual(result.dependencies.react.versions['18.1.3'], {
      'yarn.lock': '^18.1.2', // Last specifier wins for same version
    })

    deepStrictEqual(result.dependencies.react.versions['18.2.0'], {
      'yarn.lock': '^18.2.0',
    })

    // loose-envify has both direct and transitive sources
    deepStrictEqual(result.dependencies['loose-envify'].versions['1.4.0'], {
      'yarn.lock': '^1.1.0',
      'yarn.lock:react@18.2.0': '^1.1.0',
      'yarn.lock:react@18.1.3': '^1.0.9',
    })
  })

  it('tracks transitive dependency chains', () => {
    const result = parseYarnLockContent(`
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1

app@1.0.0:
  version "1.0.0"
  resolved "https://example.com/app-1.0.0.tgz"
  dependencies:
    lib-a "^2.0.0"

lib-a@^2.0.0:
  version "2.0.0"
  resolved "https://example.com/lib-a-2.0.0.tgz"
  dependencies:
    lib-b "^3.0.0"

lib-b@^3.0.0:
  version "3.0.0"
  resolved "https://example.com/lib-b-3.0.0.tgz"
  `)

    // lib-a is a transitive dep of app
    deepStrictEqual(result.dependencies['lib-a'].versions['2.0.0'], {
      'yarn.lock': '^2.0.0',
      'yarn.lock:app@1.0.0': '^2.0.0',
    })

    // lib-b is a transitive dep of lib-a
    deepStrictEqual(result.dependencies['lib-b'].versions['3.0.0'], {
      'yarn.lock': '^3.0.0',
      'yarn.lock:lib-a@2.0.0': '^3.0.0',
    })
  })
})
